1744831099-rubyforgood-casa/config/routes.rb
# frozen_string_literal: true

# def set_up_flipper
#   flipper_app = Flipper::UI.app(Flipper.instance, rack_protection: {except: :http_origin}) do |builder|
#     builder.use Rack::Auth::Basic do |username, password|
#       username == ENV["FLIPPER_USERNAME"] && password == ENV["FLIPPER_PASSWORD"]
#     end
#   end
#   mount flipper_app, at: "/flipper"
# end

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => "/api-docs"
  mount Rswag::Api::Engine => "/api-docs"

  # set_up_flipper

  devise_for :all_casa_admins, path: "all_casa_admins", controllers: {sessions: "all_casa_admins/sessions"}
  devise_for :users, controllers: {sessions: "users/sessions", passwords: "users/passwords"}
  authenticate :all_casa_admins do
    mount PgHero::Engine, at: "pg_dashboard", constraints: lambda { |request|
      admin = request.env["warden"].user(:all_casa_admin)
      admin.present? && (admin.role == "All Casa Admin" || admin.casa_admin?)
    }
  end

  concern :with_datatable do
    post "datatable", on: :collection
  end

  authenticated :all_casa_admin do
    root to: "all_casa_admins/dashboard#show", as: :authenticated_all_casa_admin_root
  end

  authenticated :user do
    root to: "dashboard#show", as: :authenticated_user_root
  end

  devise_scope :user do
    root to: "static#index"
  end

  devise_scope :all_casa_admins do
    root to: "all_casa_admins/sessions#new", as: :unauthenticated_all_casa_root
  end

  resources :preference_sets, only: [] do
    collection do
      post "/table_state_update/:table_name", to: "preference_sets#table_state_update", as: :table_state_update
      get "/table_state/:table_name", to: "preference_sets#table_state", as: :table_state
    end
  end

  resources :health, only: %i[index] do
    collection do
      get :case_contacts_creation_times_in_last_week
      get :monthly_line_graph_data
      get :monthly_unique_users_graph_data
    end
  end

  get "/.well-known/assetlinks.json", to: "android_app_associations#index"
  resources :casa_cases, except: %i[destroy] do
    resource :emancipation, only: %i[show] do
      member do
        post "save"
      end
    end

    resource :fund_request, only: %i[new create]

    resources :court_dates, only: %i[create edit new show update destroy]

    resources :placements

    member do
      patch :deactivate
      patch :reactivate
      patch :copy_court_orders
    end
  end

  resources :casa_admins, except: %i[destroy show] do
    member do
      patch :deactivate
      patch :activate
      patch :resend_invitation
      post :send_reactivation_alert
      patch :change_to_supervisor
    end
  end

  get "case_contacts/leave", to: "case_contacts#leave", as: "leave_case_contacts_form"
  get "case_contacts/drafts", to: "case_contacts#drafts"
  resources :case_contacts, except: %i[create update show] do
    member do
      post :restore
    end
    resources :form, controller: "case_contacts/form", only: %i[show update]
    resources :followups, only: %i[create], controller: "case_contacts/followups", shallow: true do
      patch :resolve, on: :member
    end
  end

  resources :contact_topic_answers, only: %i[create destroy]

  resources :reports, only: %i[index]
  get :export_emails, to: "reports#export_emails"

  resources :case_court_reports, only: %i[index show] do
    collection do
      post :generate
    end
  end
  resources :reimbursements, only: %i[index change_complete_status], concerns: %i[with_datatable] do
    patch :mark_as_complete, to: "reimbursements#change_complete_status"
    patch :mark_as_needs_review, to: "reimbursements#change_complete_status"
  end
  resources :imports, only: %i[index create] do
    collection do
      get :download_failed
    end
  end
  resources :case_contact_reports, only: %i[index]
  resources :mileage_reports, only: %i[index]
  resources :mileage_rates, only: %i[index new create edit update]
  resources :casa_org, only: %i[edit update]
  resources :contact_type_groups, only: %i[new create edit update]
  resources :contact_types, only: %i[new create edit update]
  resources :hearing_types, only: %i[new create edit update] do
    resources :checklist_items, only: %i[new create edit update destroy]
  end
  resources :emancipation_checklists, only: %i[index]
  resources :judges, only: %i[new create edit update]
  resources :notifications, only: [:index] do
    member do
      post "mark_as_read"
    end
  end
  resources :other_duties, only: %i[new create edit index update]
  resources :missing_data_reports, only: %i[index]
  resources :learning_hours_reports, only: %i[index]
  resources :learning_hour_types, only: %i[new create edit update]
  resources :learning_hour_topics, only: %i[new create edit update]

  resources :contact_topics, except: %i[index show delete] do
    delete "soft_delete", on: :member
  end

  resources :followup_reports, only: :index
  resources :placement_reports, only: :index
  resources :banners, except: %i[show] do
    member do
      get :dismiss
    end
  end
  resources :bulk_court_dates, only: %i[new create]
  resources :case_groups, only: %i[index new edit create update destroy]
  resources :learning_hours, only: %i[index show new create edit update destroy]
  namespace :learning_hours do
    resources :volunteers, only: :show
  end

  resources :supervisors, except: %i[destroy show], concerns: %i[with_datatable] do
    member do
      patch :activate
      patch :deactivate
      patch :resend_invitation
      patch :change_to_admin
    end
  end
  resources :supervisor_volunteers, only: %i[create] do
    collection do
      post :bulk_assignment
    end
    member do
      patch :unassign
    end
  end
  resources :volunteers, except: %i[destroy], concerns: %i[with_datatable] do
    post :stop_impersonating, on: :collection
    member do
      patch :activate
      patch :deactivate
      get :resend_invitation
      get :send_reactivation_alert
      patch :reminder
      get :impersonate
    end
    resources :notes, only: %i[create edit update destroy]
  end
  resources :case_assignments, only: %i[create destroy] do
    member do
      get :unassign
      patch :unassign
      patch :show_hide_contacts
      patch :reimbursement
    end
  end
  resources :case_court_orders, only: %i[destroy]

  resources :additional_expenses, only: %i[create destroy]

  namespace :all_casa_admins do
    resources :casa_orgs, only: [:new, :create, :show] do
      resources :casa_admins, only: [:new, :create, :edit, :update] do
        member do
          patch :deactivate
          patch :activate
        end
      end
    end

    resources :patch_notes, only: %i[create destroy index update]
  end

  resources :all_casa_admins, only: [:new, :create] do
    collection do
      get :edit
      patch :update
      patch "update_password"
    end
  end

  resources :users, only: [] do
    collection do
      get :edit
      patch :update
      patch "update_password"
      patch "update_email"
      patch :add_language
      delete :remove_language
    end
  end
  resources :languages, only: %i[new create edit update] do
    delete :remove_from_volunteer
  end

  direct :help_admins_supervisors do
    "https://thunder-flower-8c2.notion.site/Casa-Volunteer-Tracking-App-HelpSite-3b95705e80c742ffa729ccce7beeabfa"
  end

  direct :help_volunteers do
    "https://thunder-flower-8c2.notion.site/Casa-Volunteer-Tracking-App-HelpSite-Volunteers-c24d9d2ef8b249bbbda8192191365039?pvs=4"
  end

  get "/error", to: "error#index"

  namespace :api do
    namespace :v1 do
      namespace :users do
        post "sign_in", to: "sessions#create"
        delete "sign_out", to: "sessions#destroy"
      end
    end
  end

  constraints CanAccessFlipperUI do
    mount Flipper::UI.app(Flipper) => "/flipper"
  end
end

1744831099-rubyforgood-casa/app/models/court_date.rb
# frozen_string_literal: true

require "sablon"

class CourtDate < ApplicationRecord
  belongs_to :casa_case
  has_one :casa_org, through: :casa_case
  validates :date, presence: true
  validates :date, comparison: {
    less_than_or_equal_to: -> { 1.year.from_now },
    message: "is not valid. Court date must be within one year from today.",
    allow_nil: true
  }
  validates :date, comparison: {
    greater_than_or_equal_to: "1989-01-01".to_date,
    message: "is not valid. Court date cannot be prior to 1/1/1989.",
    allow_nil: true
  }

  has_many :case_court_orders
  belongs_to :hearing_type, optional: true
  belongs_to :judge, optional: true

  accepts_nested_attributes_for :case_court_orders, reject_if: :all_blank, allow_destroy: true

  before_save :set_court_report_due_date

  scope :ordered_ascending, -> { order("date asc") }

  # get reports associated with the case this belongs to before this court date but after the court date before this one
  def associated_reports
    prev = casa_case.court_dates.where("date < ?", date).order(:date).last
    if prev
      casa_case.court_reports.where("created_at > ?", prev.date).where("created_at < ?", date)
    else
      casa_case.court_reports.where("created_at < ?", date)
    end
  end

  def latest_associated_report
    associated_reports.order(:created_at).last
  end

  def additional_info?
    case_court_orders.any? || hearing_type || judge
  end

  def display_name
    "#{casa_case.case_number} - Court Date - #{I18n.l(date.to_date, format: :year_first)}"
  end

  private

  def set_court_report_due_date
    if date.present? && court_report_due_date.blank?
      self.court_report_due_date = date - 3.weeks
    end
  end
end
# == Schema Information
#
# Table name: court_dates
#
#  id                    :bigint           not null, primary key
#  court_report_due_date :datetime
#  date                  :datetime         not null
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  casa_case_id          :bigint           not null
#  hearing_type_id       :bigint
#  judge_id              :bigint
#
# Indexes
#
#  index_court_dates_on_casa_case_id     (casa_case_id)
#  index_court_dates_on_hearing_type_id  (hearing_type_id)
#  index_court_dates_on_judge_id         (judge_id)
#
# Foreign Keys
#
#  fk_rails_...  (casa_case_id => casa_cases.id)
#

1744831099-rubyforgood-casa/app/controllers/court_dates_controller.rb
class CourtDatesController < ApplicationController
  include CourtDateParams

  before_action :set_casa_case
  before_action :set_court_date, only: %i[edit show update destroy]
  before_action :require_organization!

  rescue_from ActiveRecord::RecordNotFound, with: -> { head :not_found }

  def show
    authorize @casa_case

    respond_to do |format|
      format.html {}
      format.docx do
        send_data generate_report_to_string(@court_date, params[:time_zone]),
          type: :docx,
          filename: "#{@court_date.display_name}.docx",
          disposition: "attachment",
          status: :ok
      end
    end
  end

  def new
    @court_date = CourtDate.new(casa_case: @casa_case)
    authorize @court_date
  end

  def edit
    authorize @court_date
  end

  def create
    @court_date = CourtDate.new(court_date_params(@casa_case).merge(casa_case: @casa_case))
    authorize @court_date

    if @court_date.save && @casa_case.save
      redirect_to casa_case_court_date_path(@casa_case, @court_date), notice: "Court date was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @court_date
    if @court_date.update(court_date_params(@casa_case))
      redirect_to casa_case_court_date_path(@casa_case, @court_date), notice: "Court date was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @court_date
    if @court_date.date > Time.now
      @court_date.destroy
      redirect_to casa_case_path(@casa_case), notice: "Court date was successfully deleted."
    else
      redirect_to casa_case_court_date_path(@casa_case, @court_date), notice: "You can delete only future court dates."
    end
  end

  private

  def set_casa_case
    @casa_case = current_organization.casa_cases.friendly.find(params[:casa_case_id])
  end

  def set_court_date
    @court_date = @casa_case.court_dates.find(params[:id])
  end

  def generate_report_to_string(court_date, time_zone)
    casa_case = court_date.casa_case
    casa_case.casa_org.open_org_court_report_template do |template_docx_file|
      args = {
        volunteer_id: current_user.volunteer? ? current_user.id : casa_case.assigned_volunteers.first&.id,
        case_id: casa_case.id,
        path_to_template: template_docx_file.to_path,
        time_zone: time_zone,
        court_date: court_date,
        case_court_orders: court_date.case_court_orders
      }
      context = CaseCourtReportContext.new(args).context
      court_report = CaseCourtReport.new(path_to_template: template_docx_file.to_path, context: context)

      court_report.generate_to_string
    end
  end
end

1744831099-rubyforgood-casa/app/helpers/court_dates_helper.rb
# frozen_string_literal: true

# Helper methods for court_dates
module CourtDatesHelper
  def when_do_we_have_court_dates(casa_case)
    return if casa_case.blank?

    court_dates = casa_case.court_dates.ordered_ascending
    date_now = Date.current

    if court_dates.blank?
      "none"
    elsif court_dates.last.date < date_now
      "past"
    elsif court_dates.first.date > date_now
      "future"
    end
  end
end

1744831099-rubyforgood-casa/app/views/court_dates/_fields.html.erb
<div class="input-style-1">
  <%= form.label :date, "Add Court Date" %>
  <%= form.date_field :date,
                      value: court_date.date&.to_date || Time.zone.now,
                      class: "form-control" %>
</div>
<div class="input-style-1">
  <%= form.label :court_report_due_date, "Add Court Report Due Date" %>
  <%= form.date_field :court_report_due_date,
                      value: court_date.court_report_due_date&.to_date,
                      class: "form-control" %>
</div>
<div class="select-style-1">
  <%= form.label :judge_id, "Judge" %>
  <div class="select-position">
    <%= form.collection_select(
          :judge_id,
          Judge.for_organization(current_organization),
          :id, :name,
          {include_hidden: false, include_blank: "-Select Judge-"},
          {class: "form-control"}
        ) %>
  </div>
</div>
<div class="select-style-1">
  <%= form.label :hearing_type_id, "Hearing type" %>
  <div class="select-position">
    <%= form.collection_select(
          :hearing_type_id,
          HearingType.active.for_organization(current_organization),
          :id, :name,
          {include_hidden: false, include_blank: "-Select Hearing Type-"},
          {class: "form-control"}
        ) %>
  </div>
</div>
<div class="field form-group court-orders">
  <%= render partial: "shared/court_order_list",
             locals: {casa_case: casa_case, siblings_casa_cases: nil, form: form, resource: 'court_date'} %>
</div>

1744831099-rubyforgood-casa/app/views/court_dates/_form.html.erb
<div class="card-style mb-30">
  <%= form_with(model: court_date, url: [casa_case, court_date], local: true,
    data: { controller: "court-order-form", nested_form_wrapper_selector_value: ".nested-form-wrapper" }) do |form| %>
    <%= render "/shared/error_messages", resource: court_date %>
    <div class="row align-items-center">
      <div class="col-md-6">
        <h6><strong>Case Number:</strong> <%= link_to casa_case.case_number, casa_case %></h6>
      </div>
      <div class="col-md-6">
        <div class="breadcrumb-wrapper">
          <span class="top-page-actions ml-5">
            <%= button_tag(
            type: "submit",
            class: "btn-sm main-btn primary-btn btn-hover"
          ) do %>
              <% if court_date.persisted? %>
                <i class="lni lni-pencil-alt"></i>
                Update
              <% else %>
                <i class="lni lni-plus"></i>
                Create
              <% end %>
            <% end %>
          </span>
        </div>
      </div>
    </div>
    <div class="row align-items-center">
      <%= render 'court_dates/fields', court_date: court_date, form: form, casa_case: casa_case %>
    </div>
  <% end %>
</div>

1744831099-rubyforgood-casa/app/views/court_dates/edit.html.erb
<div class="title-wrapper pt-30">
  <div class="row align-items-center">
    <div class="col-md-6">
      <div class="title mb-30">
        <h1>Editing Court Date</h1>
      </div>
    </div>
  </div>
</div>

<%= render 'form', casa_case: @casa_case, court_date: @court_date %>

1744831099-rubyforgood-casa/app/views/court_dates/new.html.erb
<div class="title-wrapper pt-30">
  <div class="row align-items-center">
    <div class="col-md-6">
      <div class="title mb-30">
        <h1>New Court Date</h1>
      </div>
    </div>
  </div>
</div>

<%= render 'form', casa_case: @casa_case, court_date: @court_date %>

1744831099-rubyforgood-casa/app/views/court_dates/show.html.erb
<div class="title-wrapper pt-30">
  <div class="row align-items-center">
    <div class="col-md-6">
      <div class="title mb-30">
        <h1>Court Date</h1>
        <time datetime="<%= @court_date.date %>" class="d-inline-block h4"><%= @court_date.decorate.formatted_date %></time>
      </div>
    </div>
    <div class="col-md-6">
      <div class="breadcrumb-wrapper mb-30">
        <%= link_to edit_casa_case_court_date_path(@casa_case, @court_date), class: "btn-sm main-btn primary-btn btn-hover" do %>
          <i class="lni lni-pencil-alt mr-10"></i>
          Edit
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-12">
  <div class="card-style mb-30">
    <dl>
      <dt>
        <h6>Case Number:</h6>
      </dt>
      <dd class="mb-3"><%= link_to "#{@casa_case.case_number}", casa_case_path(@casa_case) %></dd>
      <dt>
        <h6>Court Report Due Date:</h6>
      </dt>
      <dd class="mb-3"><%= I18n.l(@court_date.court_report_due_date, format: :full, default: "None") %></dd>
      <dt>
        <h6>Judge:</h6>
      </dt>
      <dd class="mb-3"><%= @court_date.judge&.name || "None" %></dd>
      <dt>
        <h6>Hearing Type:</h6>
      </dt>
      <dd class="mb-3"><%= @court_date.hearing_type&.name || "None" %></dd>
    </dl>
    <h6>Court Orders:</h6>
    <% if @court_date.case_court_orders.any? %>
      <div class="table-wrapper table-responsive">
        <table class="table striped-table">
          <thead>
            <th>Case Order Text</th>
            <th class="text-center">Implementation Status</th>
          </thead>
          <tbody>
            <% @court_date.case_court_orders.each do |court_order| %>
              <tr>
                <td class="min-width"><%= court_order.text %></td>
                <td class="text-center"><%= court_order.implementation_status&.humanize %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <p>
        There are no court orders associated with this court date.
      </p>
    <% end %>
    <div class="d-flex">
      <%= link_to casa_case_court_date_path(@casa_case, @court_date, format: :docx), class: "btn-sm main-btn primary-btn btn-hover" do %>
        <i class="lni lni-download mr-10"></i>
        Download Report (.docx)
      <% end %>
      <% if policy(:court_date).destroy? && @court_date.date > Time.now %>
        <%= link_to [@casa_case, @court_date], method: :delete, data: { confirm: 'Are you sure?' },class: "btn-sm main-btn danger-btn-outline btn-hover ms-auto" do %>
          <i class="lni lni-trash-can mr-10"></i>
          Delete Future Court Date
        <% end %>
      <% end %>
    </div>
  </div>
</div>